#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <nfc_blank_card_icons.h>

int32_t nfc_blank_card_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm nfc_blank_card!");

    return 0;
}
